// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/keyapi/key.proto

/*
Package keyapi is a generated protocol buffer package.

It is generated from these files:
	pkg/keyapi/key.proto

It has these top-level messages:
*/
package keyapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Key service

type KeyClient interface {
}

type keyClient struct {
	cc *grpc.ClientConn
}

func NewKeyClient(cc *grpc.ClientConn) KeyClient {
	return &keyClient{cc}
}

// Server API for Key service

type KeyServer interface {
}

func RegisterKeyServer(s *grpc.Server, srv KeyServer) {
	s.RegisterService(&_Key_serviceDesc, srv)
}

var _Key_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keyapi.Key",
	HandlerType: (*KeyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "pkg/keyapi/key.proto",
}

func init() { proto.RegisterFile("pkg/keyapi/key.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 59 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0xc8, 0x4e, 0xd7,
	0xcf, 0x4e, 0xad, 0x4c, 0x2c, 0xc8, 0x04, 0x51, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c,
	0x10, 0x11, 0x23, 0x56, 0x2e, 0x66, 0xef, 0xd4, 0xca, 0x24, 0x36, 0xb0, 0xa8, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xaa, 0x77, 0x6a, 0xdc, 0x2d, 0x00, 0x00, 0x00,
}
